[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#0B1220"
secondaryBackgroundColor = "#111827"
textColor = "#E5E7EB"
font = "sans serif"

[server]
runOnSave = true

[client]
toolbarMode = "minimal"
